services:
  tmf629:
    build:
      context: .
      dockerfile: ./oda/tmf629/Dockerfile
    container_name: go-oda-tmf629
    image: jom6768/go-oda-tmf629:latest
    ports:
      - "8629:8629"

  tmf632:
    build:
      context: .
      dockerfile: ./oda/tmf632/Dockerfile
    container_name: go-oda-tmf632
    image: jom6768/go-oda-tmf632:latest
    ports:
      - "8632:8632"
