# TMF632 Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tmf632
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tmf632
  template:
    metadata:
      labels:
        app: tmf632
    spec:
      containers:
      - name: go-oda-tmf632
        image: jom6768/go-oda-tmf632:latest
        ports:
        - containerPort: 8081

---

# TMF632 Service
apiVersion: v1
kind: Service
metadata:
  name: tmf632
spec:
  type: NodePort
  selector:
    app: tmf632  # Match the selector with the app labels in your pods
  ports:
    - port: 8081        # Port on which the service is exposed within the cluster
      targetPort: 8081   # Port on which the Go API container is listening
      nodePort: 30005    # External port on Minikube (in the 30000-32767 range)
