# TMF632 Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tmf632
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tmf632
  template:
    metadata:
      labels:
        app: tmf632
    spec:
      containers:
      - name: tmf632
        image: jom6768/go-oda-tmf632:latest
        ports:
        - containerPort: 8081
        env:
        - name: DB_HOST
          value: "localhost"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "user"
        - name: DB_PASSWORD
          value: "password"
        - name: DB_NAME
          value: "go_oda"

---

# TMF632 Service
apiVersion: v1
kind: Service
metadata:
  name: tmf632
spec:
  selector:
    app: tmf632  # Match the selector with the app labels in your pods
  ports:
    - protocol: TCP
      port: 8081  # Internal port within the cluster
      targetPort: 8081  # The port your container is listening on
  type: ClusterIP  # Default type, internal access only
