# TMF669 Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tmf669
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tmf669
  template:
    metadata:
      labels:
        app: tmf669
    spec:
      containers:
      - name: tmf669
        image: jom6768/go-oda-tmf669:latest
        ports:
        - containerPort: 8082
        env:
        - name: DB_HOST
          value: "localhost"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "user"
        - name: DB_PASSWORD
          value: "password"
        - name: DB_NAME
          value: "go_oda"

---

# TMF669 Service
apiVersion: v1
kind: Service
metadata:
  name: tmf669
spec:
  selector:
    app: tmf669  # Match the selector with the app labels in your pods
  ports:
    - protocol: TCP
      port: 8082  # Internal port within the cluster
      targetPort: 8082  # The port your container is listening on
  type: ClusterIP  # Default type, internal access only
