# TMF632 Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tmf632
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tmf632
  template:
    metadata:
      labels:
        app: tmf632
    spec:
      containers:
      - name: tmf632
        image: go-oda-tmf632:latest
        imagePullSecrets:
        - name: regcred
        ports:
        - containerPort: 8081
        env:
        - name: DATABASE_URL
          value: "postgres://user:password@postgres:5432/go_oda?sslmode=disable"

---

# TMF632 Service
apiVersion: v1
kind: Service
metadata:
  name: tmf632
spec:
  selector:
    app: tmf632  # Match the selector with the app labels in your pods
  ports:
    - protocol: TCP
      port: 8081  # Internal port within the cluster
      targetPort: 8081  # The port your container is listening on
  type: ClusterIP  # Default type, internal access only