name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.23.1'

    - name: Install dependencies
      run: go mod download

    - name: Build
      run: |
        go build -o tmf632 ./oda/tmf632
        go build -o tmf669 ./oda/tmf669

    - name: Test
      run: go test ./...

    - name: Build Docker images
      run: |
        docker build -t go-oda-tmf632 -f Dockerfile .
        docker build -t go-oda-tmf669 -f Dockerfile .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Setup Kubectl
      uses: azure/setup-kubectl@v1
    - name: Deploy to Minikube
      run: |
        kubectl apply -f k8s/