name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Setup Go
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23.1

      - name: Install dependencies
        run: go mod download

      # Build Docker images
      - name: Build Docker Image
        run: |
          docker build . --no-cache -t jom6768/go-oda-tmf632 -f Dockerfile

      # Push Docker images
      - name: Push Docker Image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker push jom6768/go-oda-tmf632:latest

      # Run any tests
      - name: Test
        run: go test ./...

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Setup Kubectl
      uses: azure/setup-kubectl@v1
    - name: Deploy to Minikube
      # kubectl apply -f k8s/deployment-postgresql.yaml
      run: |
        kubectl apply -f k8s/deployment-tmf632.yaml
        kubectl port-forward svc/tmf632 8081:8081
