name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Setup Go
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23.1

      - name: Install dependencies
        run: go mod tidy

      # Build Docker images
      - name: Build Docker Image
        run: |
          docker build -t go-oda-tmf632:latest -f Dockerfile-tmf632 .
          docker build -t go-oda-tmf669:latest -f Dockerfile-tmf669 .

      # Push Docker images
      - name: Push Docker Image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker tag go-oda-tmf632:latest jom6768/go-oda-tmf632:latest
          docker push jom6768/go-oda-tmf632:latest
          docker tag go-oda-tmf669:latest jom6768/go-oda-tmf669:latest
          docker push jom6768/go-oda-tmf669:latest

      # Run any tests
      - name: Test
        run: go test ./...

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Setup Kubectl
      uses: azure/setup-kubectl@v1
    - name: Deploy to Minikube
      run: |
        kubectl apply -f k8s/deployment-postgresql.yaml
        kubectl apply -f k8s/deployment-tmf632.yaml
        kubectl apply -f k8s/deployment-tmf669.yaml
