name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Setup Go
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.23.1'

    - name: Install dependencies
      run: go mod download

    # Build Docker images
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build Docker images
      run: |
        docker build -t go-oda-tmf632:latest -f Dockerfile .
        docker build -t go-oda-tmf669:latest -f Dockerfile .

    # Run the containers to verify they work
    - name: Run tmf632 container
      run: docker run -d -p 8081:8081 --name tmf632-container go-oda-tmf632:latest

    - name: Run tmf669 container
      run: docker run -d -p 8082:8082 --name tmf669-container go-oda-tmf669:latest

    # Run any tests to validate the containers are running
    - name: Test tmf632 container
      run: curl -f http://localhost:8081 || exit 1

    - name: Test tmf669 container
      run: curl -f http://localhost:8082 || exit 1

    - name: Test
      run: go test ./...

    # Clean up containers after the tests
    - name: Clean up Docker containers
      run: |
        docker stop tmf632-container
        docker stop tmf669-container
        docker rm tmf632-container
        docker rm tmf669-container

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Setup Kubectl
      uses: azure/setup-kubectl@v1
    - name: Deploy to Minikube
      run: |
        kubectl apply -f k8s/