name: CI/CD Pipeline

on:
  push:
    branches:
      - oda
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.23.1'

    - name: Install dependencies
      run: go mod download

    - name: Build
      run: |
        go build -o tmf632 ./oda/tmf632
        go build -o tmf669 ./oda/tmf669

    - name: Test
      run: go test ./...

    - name: Build Docker images
      run: |
        docker build -t go-oda-tmf632:latest -f Dockerfile .
        docker tag go-oda-tmf632:latest jom6768/go-oda-tmf632:latest
        docker push jom6768/go-oda-tmf632:latest
        docker build -t go-oda-tmf669:latest -f Dockerfile .
        docker tag go-oda-tmf669:latest jom6768/go-oda-tmf669:latest
        docker push jom6768/go-oda-tmf669:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Setup Kubectl
      uses: azure/setup-kubectl@v1
    - name: Deploy to Minikube
      run: |
        kubectl apply -f k8s/postgresql-deployment.yaml
        kubectl apply -f k8s/tmf632-deployment.yaml
        kubectl apply -f k8s/tmf669-deployment.yaml